/**
 * Audio (Tone.js): music, hit / miss feedback, and above all the reference CLOCK.
 *
 * Game timing runs on `Tone.now()` (the audio context clock, far steadier than
 * performance.now() for rhythm). Rendering stays on requestAnimationFrame: the
 * two are decoupled, so a dropped frame never shifts the music.
 *
 * The soundtrack is GENERATED by Tone.js (no asset, no licensing) and arranged
 * per phase: phase 1 minimal, phase 2 drums and bass, phase 3 the full thing
 * with a lead. It starts on the same audio instant as the targets, so beatmap
 * notes fall on the musical grid, like Osu!.
 *
 * To play over your own music: set VITE_MUSIC_URL (see settings.ts).
 */

import * as Tone from 'tone';
import { settings } from '../config/settings';
import type { Grade } from '../game/types';

const COMBO_SCALE = ['C5', 'D5', 'E5', 'G5', 'A5', 'C6', 'D6', 'E6'] as const;

/** The generated track's grid: 2 bars of 8 eighth notes, in A minor. */
const BASS_LINE = ['A1', 'A1', 'E2', 'A1', 'F1', 'F1', 'C2', 'G1'] as const;
const LEAD_LINE = ['A4', 'C5', 'E5', 'C5', 'F4', 'A4', 'C5', 'G4'] as const;
const PAD_CHORDS = [
  ['A3', 'C4', 'E4'],
  ['F3', 'A3', 'C4'],
] as const;

export class AudioEngine {
  private perfectSynth: Tone.PolySynth<Tone.Synth> | null = null;
  private goodSynth: Tone.PolySynth<Tone.Synth> | null = null;
  private missSynth: Tone.NoiseSynth | null = null;
  private missTone: Tone.Synth | null = null;
  private metroSynth: Tone.MembraneSynth | null = null;
  private reverbSend: Tone.Reverb | null = null;
  private reverbBus: Tone.Gain | null = null;

  /* Instruments of the generated track. */
  private kick: Tone.MembraneSynth | null = null;
  private snare: Tone.NoiseSynth | null = null;
  private hat: Tone.NoiseSynth | null = null;
  private bass: Tone.MonoSynth | null = null;
  private lead: Tone.PolySynth<Tone.Synth> | null = null;
  private pad: Tone.PolySynth<Tone.Synth> | null = null;
  private musicPart: Tone.Loop | null = null;
  private metroLoop: Tone.Loop | null = null;
  private player: Tone.Player | null = null;

  /** Current phase (0..2): drives the arrangement. */
  private intensity = 0;
  /** Current eighth note since the track started. */
  private step = 0;
  private initialized = false;

  get ready(): boolean {
    return this.initialized;
  }

  /** Must be called INSIDE a user gesture, or the audio context stays suspended. */
  async init(): Promise<void> {
    if (this.initialized) return;
    await Tone.start();
    Tone.Destination.volume.value = settings.MASTER_VOLUME;

    /*
     * Effect bus in PARALLEL, never in series.
     *
     * Tone.Reverb is a convolver whose impulse response is generated
     * asynchronously: until it exists, anything routed ONLY through it outputs
     * silence. So instruments go straight to the output and merely send a copy
     * into the reverb (wet = 1, dosed by the bus gain).
     */
    const reverbBus = new Tone.Gain(0.25).toDestination();
    const reverb = new Tone.Reverb({ decay: 1.4, wet: 1 }).connect(reverbBus);
    // Wait for the IR: without this the first seconds of play have no tail.
    await reverb.generate();
    this.reverbSend = reverb;
    this.reverbBus = reverbBus;

    /* ---- Game feedback ---------------------------------------------------- */

    // "Perfect" hit: bright, short ping.
    this.perfectSynth = new Tone.PolySynth(Tone.Synth, {
      oscillator: { type: 'triangle' },
      envelope: { attack: 0.001, decay: 0.16, sustain: 0, release: 0.12 },
    }).toDestination();
    this.perfectSynth.connect(reverb);
    this.perfectSynth.volume.value = -2;

    // "Good" hit: duller and shorter.
    this.goodSynth = new Tone.PolySynth(Tone.Synth, {
      oscillator: { type: 'sine' },
      envelope: { attack: 0.002, decay: 0.11, sustain: 0, release: 0.08 },
    }).toDestination();
    this.goodSynth.connect(reverb);
    this.goodSynth.volume.value = -6;

    // Miss: dry thud plus a falling tone. Deliberately unpleasant.
    this.missSynth = new Tone.NoiseSynth({
      noise: { type: 'brown' },
      envelope: { attack: 0.002, decay: 0.22, sustain: 0 },
    }).connect(new Tone.Filter({ frequency: 1200, type: 'lowpass' }).toDestination());
    this.missSynth.volume.value = -12;

    this.missTone = new Tone.Synth({
      oscillator: { type: 'sawtooth' },
      envelope: { attack: 0.004, decay: 0.28, sustain: 0, release: 0.1 },
    }).toDestination();
    this.missTone.volume.value = -20;

    // Metronome / count-in.
    this.metroSynth = new Tone.MembraneSynth({
      pitchDecay: 0.02,
      octaves: 4,
      envelope: { attack: 0.001, decay: 0.16, sustain: 0 },
    }).toDestination();
    this.metroSynth.volume.value = -14;

    this.metroLoop = new Tone.Loop((time) => {
      if (settings.METRONOME_ON) this.metroSynth?.triggerAttackRelease('C2', '16n', time);
    }, '4n');

    /* ---- Track ------------------------------------------------------------ */
    this.buildMusic(reverb);

    this.initialized = true;
  }

  /** Check blip: confirms by ear that the audio output works at all. */
  playTestBlip(): void {
    this.metroSynth?.triggerAttackRelease('C4', '16n');
  }

  /** Builds the track's instruments and its sequencing loop. */
  private buildMusic(reverb: Tone.Reverb): void {
    this.kick = new Tone.MembraneSynth({
      pitchDecay: 0.045,
      octaves: 6,
      envelope: { attack: 0.001, decay: 0.32, sustain: 0 },
    }).toDestination();
    this.kick.volume.value = -6;

    this.snare = new Tone.NoiseSynth({
      noise: { type: 'white' },
      envelope: { attack: 0.001, decay: 0.16, sustain: 0 },
    }).toDestination();
    this.snare.volume.value = -18;

    this.hat = new Tone.NoiseSynth({
      noise: { type: 'white' },
      envelope: { attack: 0.001, decay: 0.03, sustain: 0 },
    }).connect(new Tone.Filter({ frequency: 7000, type: 'highpass' }).toDestination());
    this.hat.volume.value = -26;

    this.bass = new Tone.MonoSynth({
      oscillator: { type: 'square' },
      filter: { Q: 2, type: 'lowpass' },
      envelope: { attack: 0.005, decay: 0.18, sustain: 0.25, release: 0.2 },
      filterEnvelope: { attack: 0.005, decay: 0.12, sustain: 0.3, baseFrequency: 120, octaves: 2.5 },
    }).toDestination();
    this.bass.volume.value = -14;

    // Same routing as the game sounds: direct output plus a reverb copy.
    this.lead = new Tone.PolySynth(Tone.Synth, {
      oscillator: { type: 'triangle' },
      envelope: { attack: 0.005, decay: 0.2, sustain: 0.05, release: 0.2 },
    }).toDestination();
    this.lead.connect(reverb);
    this.lead.volume.value = -18;

    this.pad = new Tone.PolySynth(Tone.Synth, {
      oscillator: { type: 'sine' },
      envelope: { attack: 0.6, decay: 0.4, sustain: 0.5, release: 1.2 },
    }).toDestination();
    this.pad.connect(reverb);
    this.pad.volume.value = -22;

    // One eighth note at a time. The arrangement reads `this.intensity` to know
    // which instruments play, so a phase change reshapes the track without
    // interrupting it.
    this.musicPart = new Tone.Loop((time) => {
      const step = this.step % 8;
      const bar = Math.floor(this.step / 8) % 2;
      this.step += 1;
      if (this.player) return; // custom track: no generated layer on top

      // Pad: every 2 bars, present from phase 1.
      if (step === 0) {
        const chord = PAD_CHORDS[bar] ?? PAD_CHORDS[0];
        this.pad?.triggerAttackRelease([...chord], '2n', time);
      }

      // Drums: kick on the beat, snare on 2 and 4 from phase 2.
      if (step % 4 === 0) this.kick?.triggerAttackRelease('C1', '8n', time);
      if (this.intensity >= 1 && step === 4) this.snare?.triggerAttackRelease('16n', time);
      if (this.intensity >= 1 && step % 2 === 1) this.hat?.triggerAttackRelease('64n', time);

      // Bass: phase 2 and up.
      if (this.intensity >= 1) {
        const note = BASS_LINE[step] ?? 'A1';
        this.bass?.triggerAttackRelease(note, '8n', time);
      }

      // Lead: phase 3 only, doubled on the second bar.
      if (this.intensity >= 2) {
        const note = LEAD_LINE[step] ?? 'A4';
        this.lead?.triggerAttackRelease(note, '16n', time);
        if (bar === 1 && step % 2 === 0) {
          this.lead?.triggerAttackRelease(note, '32n', time + Tone.Time('16n').toSeconds());
        }
      }
    }, '8n');
  }

  /** The game's reference clock, in seconds. */
  now(): number {
    return Tone.now();
  }

  setBpm(bpm: number): void {
    Tone.Transport.bpm.value = bpm;
  }

  /**
   * Loads a custom music track (VITE_MUSIC_URL). If the URL is missing or the
   * file cannot be fetched, the generated track is used instead.
   */
  async loadTrack(url: string | undefined): Promise<void> {
    if (!url) return;
    try {
      const player = new Tone.Player({ url, loop: false }).toDestination();
      await Tone.loaded();
      player.volume.value = settings.MUSIC_VOLUME;
      this.player = player;
    } catch (err) {
      console.warn('[fingertune] custom track not found, using the generated one:', err);
      this.player = null;
    }
  }

  /**
   * Starts the music and returns the exact audio instant of the run's t=0, so
   * the engine can line its targets up with it.
   *
   * @param delay margin (s) before the start, to schedule the events.
   */
  startMusic(delay = 0.15): number {
    const startAt = Tone.now() + delay;
    this.step = 0;
    this.intensity = 0;

    Tone.Transport.stop();
    Tone.Transport.cancel();
    Tone.Transport.position = 0;
    // stop() before start(): on a replay (key R) the Loops are already in the
    // "started" state, and start() alone would not reschedule them after cancel().
    this.musicPart?.stop(0);
    this.metroLoop?.stop(0);
    this.musicPart?.start(0);
    this.metroLoop?.start(0);

    // The music comes in when the countdown ends; the countdown gets a count-in.
    if (this.player) {
      this.player.stop();
      this.player.start(startAt + settings.COUNTDOWN);
    } else {
      Tone.Transport.start(startAt + settings.COUNTDOWN);
    }

    for (let i = 0; i < Math.floor(settings.COUNTDOWN); i++) {
      this.metroSynth?.triggerAttackRelease('C3', '32n', startAt + i);
    }

    return startAt;
  }

  stopMusic(): void {
    Tone.Transport.stop();
    this.player?.stop();
  }

  /** Steps the arrangement up (called on a phase change). */
  setIntensity(level: number): void {
    this.intensity = Math.max(0, Math.min(2, level));
  }

  /** Hit sound. The pitch climbs with the combo, to reward streaks. */
  playHit(grade: Exclude<Grade, 'MISS'>, combo: number): void {
    if (!this.initialized) return;
    const note = COMBO_SCALE[Math.min(combo, COMBO_SCALE.length - 1)] ?? 'C5';
    if (grade === 'PERFECT') this.perfectSynth?.triggerAttackRelease([note, 'G6'], '32n');
    else this.goodSynth?.triggerAttackRelease(note, '32n');
  }

  /** Miss sound. Heavier when it breaks a combo. */
  playMiss(brokeCombo: boolean): void {
    if (!this.initialized) return;
    const time = Tone.now();
    this.missSynth?.triggerAttackRelease('8n', time);
    if (brokeCombo && this.missTone) {
      // Falling pitch, the "combo break" cue.
      this.missTone.triggerAttackRelease('A3', '8n', time);
      this.missTone.frequency.rampTo('D3', 0.22, time);
    }
  }

  dispose(): void {
    this.musicPart?.dispose();
    this.metroLoop?.dispose();
    for (const node of [
      this.perfectSynth,
      this.goodSynth,
      this.missSynth,
      this.missTone,
      this.metroSynth,
      this.reverbSend,
      this.reverbBus,
      this.kick,
      this.snare,
      this.hat,
      this.bass,
      this.lead,
      this.pad,
      this.player,
    ]) {
      node?.dispose();
    }
    this.initialized = false;
  }
}
