/**
 * Draws public/og-card.png, the card LinkedIn, Slack and Discord show for a link.
 *
 * Why this exists: a link posted without one renders as a grey box with a
 * domain in it, and the whole point of posting the playable URL rather than the
 * repository is that someone sees the game and presses play. For most people
 * the card is the only part of the project they will ever look at.
 *
 * Two halves, and the split is the point.
 *
 * Node draws the background, the rules and the sprite. The sprite is read out
 * of assets/logo.svg — which is a bitmap written in XML — and scaled by a whole
 * number, so re-colouring the logo re-colours the card and no pixel is ever
 * half a pixel. That part *should* be blocky: it is a 16x16 icon.
 *
 * ffmpeg draws the type, through FreeType and HarfBuzz. An earlier version drew
 * the text here too, from a 5x7 alphabet defined in this file, and that was the
 * wrong call. A card is read at roughly half size in a feed, and hand-drawn
 * glyphs at that scale stop looking like a decision and start looking like a
 * compression artefact. The wordmark on the site can afford a bitmap face
 * because it is one word at 36px; a card carrying a sentence cannot.
 *
 * Which is why this script is no longer part of `prebuild`. It needs ffmpeg
 * built with libfreetype, and the CI image does not promise one. The card is a
 * designed asset, committed like the logo, and regenerated by hand when the
 * sprite or the wording changes:
 *
 *   npm run build:og
 *
 * Fonts: Inter, SIL Open Font License, in scripts/fonts (licence alongside).
 */

import { deflateSync } from 'node:zlib';
import { readFileSync, writeFileSync, mkdtempSync, mkdirSync, rmSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { tmpdir } from 'node:os';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');

/* The card, and the palette it shares with the game (see config/settings.ts). */
const WIDTH = 1200;
const HEIGHT = 630;
const INK = [0x16, 0x16, 0x2a];
const INK_SOFT = [0x61, 0x61, 0x7a];
const PAPER = [0xff, 0xff, 0xff];
const PINK = [0xff, 0x5e, 0xdb];
const CYAN = [0x4d, 0xd8, 0xff];

/* ------------------------------------------------------------------ canvas -- */

/** A plain RGB framebuffer. Three bytes per pixel, row-major. */
function createCanvas(width, height, fill) {
  const pixels = Buffer.alloc(width * height * 3);
  for (let i = 0; i < width * height; i++) {
    pixels[i * 3] = fill[0];
    pixels[i * 3 + 1] = fill[1];
    pixels[i * 3 + 2] = fill[2];
  }
  return { width, height, pixels };
}

function fillRect(canvas, x, y, w, h, color) {
  const x0 = Math.max(0, Math.round(x));
  const y0 = Math.max(0, Math.round(y));
  const x1 = Math.min(canvas.width, Math.round(x + w));
  const y1 = Math.min(canvas.height, Math.round(y + h));
  for (let py = y0; py < y1; py++) {
    for (let px = x0; px < x1; px++) {
      const at = (py * canvas.width + px) * 3;
      canvas.pixels[at] = color[0];
      canvas.pixels[at + 1] = color[1];
      canvas.pixels[at + 2] = color[2];
    }
  }
}

/* -------------------------------------------------------------------- logo -- */

/**
 * The logo, read out of its own SVG.
 *
 * The sprite is a list of axis-aligned rects on a 16x16 grid, which is exactly
 * a bitmap written in XML: parsing it back is a dozen lines and means the card
 * can never show a logo the site does not.
 */
function readLogo() {
  const svg = readFileSync(join(root, 'assets', 'logo.svg'), 'utf8');
  const grid = Array.from({ length: 16 }, () => Array(16).fill(null));
  const rect =
    /<rect\s+x="(\d+)"\s+y="(\d+)"\s+width="(\d+)"\s+height="(\d+)"\s+fill="#([0-9a-fA-F]{6})"/g;

  let match;
  let count = 0;
  while ((match = rect.exec(svg)) !== null) {
    const [, xs, ys, ws, hs, hex] = match;
    const color = [
      parseInt(hex.slice(0, 2), 16),
      parseInt(hex.slice(2, 4), 16),
      parseInt(hex.slice(4, 6), 16),
    ];
    for (let y = Number(ys); y < Number(ys) + Number(hs); y++) {
      for (let x = Number(xs); x < Number(xs) + Number(ws); x++) {
        if (grid[y] && x < 16) grid[y][x] = color;
      }
    }
    count++;
  }

  if (count === 0) throw new Error('assets/logo.svg: no <rect> matched — has the sprite changed?');
  return grid;
}

function drawLogo(canvas, grid, x, y, scale) {
  for (let gy = 0; gy < 16; gy++) {
    for (let gx = 0; gx < 16; gx++) {
      const color = grid[gy][gx];
      if (color) fillRect(canvas, x + gx * scale, y + gy * scale, scale, scale, color);
    }
  }
}

/* --------------------------------------------------------------------- png -- */

const CRC_TABLE = (() => {
  const table = new Int32Array(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    table[n] = c;
  }
  return table;
})();

function crc32(buffer) {
  let c = 0xffffffff;
  for (const byte of buffer) c = CRC_TABLE[(c ^ byte) & 0xff] ^ (c >>> 8);
  return (c ^ 0xffffffff) >>> 0;
}

function chunk(type, data) {
  const length = Buffer.alloc(4);
  length.writeUInt32BE(data.length);
  const body = Buffer.concat([Buffer.from(type, 'ascii'), data]);
  const crc = Buffer.alloc(4);
  crc.writeUInt32BE(crc32(body));
  return Buffer.concat([length, body, crc]);
}

/** Truecolour, 8 bits per channel, no filtering — the image is flat colour. */
function encodePng({ width, height, pixels }) {
  const header = Buffer.alloc(13);
  header.writeUInt32BE(width, 0);
  header.writeUInt32BE(height, 4);
  header[8] = 8; // bit depth
  header[9] = 2; // colour type: truecolour
  header[10] = 0; // deflate
  header[11] = 0; // adaptive filtering
  header[12] = 0; // no interlace

  // One filter byte per scanline. Filter 0 (None) compresses well here because
  // the image is large flat areas, and it keeps this function readable.
  const stride = width * 3;
  const raw = Buffer.alloc(height * (stride + 1));
  for (let y = 0; y < height; y++) {
    raw[y * (stride + 1)] = 0;
    pixels.copy(raw, y * (stride + 1) + 1, y * stride, (y + 1) * stride);
  }

  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    chunk('IHDR', header),
    chunk('IDAT', deflateSync(raw, { level: 9 })),
    chunk('IEND', Buffer.alloc(0)),
  ]);
}

/* ------------------------------------------------------------- background --- */

const canvas = createCanvas(WIDTH, HEIGHT, PAPER);

// Two rules, in the logo's own two colours. A white card needs an edge or it
// dissolves into a white feed, and this is the quietest one available.
fillRect(canvas, 0, 0, WIDTH, 12, PINK);
fillRect(canvas, 0, HEIGHT - 12, WIDTH, 12, CYAN);

// The sprite, at 12x — a whole number, so no pixel is half a pixel.
const LOGO_SCALE = 12;
const LOGO_SIZE = 16 * LOGO_SCALE;
drawLogo(canvas, readLogo(), 110, Math.round((HEIGHT - LOGO_SIZE) / 2), LOGO_SCALE);

const scratch = mkdtempSync(join(tmpdir(), 'fingertune-og-'));
const base = join(scratch, 'base.png');
writeFileSync(base, encodePng(canvas));

/* -------------------------------------------------------------------- type -- */

const hex = (rgb) => '0x' + rgb.map((c) => c.toString(16).padStart(2, '0')).join('');

/*
 * A left-aligned column beside the sprite.
 *
 * Three lines and no more. The card is seen at about 600px wide, so the
 * smallest thing here still lands around 13px — which is the floor for
 * something a reader is expected to actually read rather than recognise.
 */
const TEXT_X = 384;
const lines = [
  { text: 'Fingertune', font: 'inter-800.ttf', size: 96, y: 206, color: INK },
  {
    text: 'A rhythm game you play by pinching',
    font: 'inter-400.ttf',
    size: 38,
    y: 332,
    color: INK,
  },
  {
    text: 'Webcam only. Nothing is uploaded.',
    font: 'inter-400.ttf',
    size: 27,
    y: 398,
    color: INK_SOFT,
  },
];

/*
 * Each line goes through `textfile=` rather than `text=`, and every path in the
 * filter is relative to the repository root.
 *
 * Both halves of that are forced by the filter grammar. It treats `:` as its
 * option separator and `\` as its escape, which is most of a Windows path — an
 * absolute `C:\Users\…` is parsed as an option named `C`. And it treats commas
 * and quotes as syntax inside values too, so quoting the text does not help:
 * an earlier version wrapped each string and ffmpeg faithfully drew the
 * quotation marks onto the card.
 *
 * A relative path has no drive colon, and a file has no grammar at all.
 */
const stage = join(root, '.og-build');
mkdirSync(stage, { recursive: true });

const filter = lines
  .map((l, i) => {
    writeFileSync(join(stage, `line${i}.txt`), l.text, 'utf8');
    return (
      `drawtext=fontfile=scripts/fonts/${l.font}:textfile=.og-build/line${i}.txt` +
      `:fontsize=${l.size}:fontcolor=${hex(l.color)}:x=${TEXT_X}:y=${l.y}`
    );
  })
  .join(',');

const out = join(root, 'public', 'og-card.png');

try {
  // cwd is the repository root, which is what makes the relative paths above
  // resolve. The input and output are passed as arguments, not filter values,
  // so they are free to be absolute.
  execFileSync('ffmpeg', ['-v', 'error', '-i', base, '-vf', filter, '-frames:v', '1', '-y', out], {
    cwd: root,
    stdio: ['ignore', 'inherit', 'inherit'],
  });
} catch (err) {
  throw new Error(
    'ffmpeg failed. This script needs ffmpeg built with libfreetype — check\n' +
      '  ffmpeg -filters | grep drawtext\n' +
      String(err.message ?? err),
  );
} finally {
  rmSync(stage, { recursive: true, force: true });
  rmSync(scratch, { recursive: true, force: true });
}

console.log(`[fingertune] wrote ${out} (${WIDTH}x${HEIGHT})`);
