/// <reference types="vite/client" />

interface ImportMetaEnv {
  /** URL of the hand_landmarker.task model (default: Google's CDN). */
  readonly VITE_HAND_MODEL_URL?: string;
  /** Folder holding the MediaPipe wasm binaries (default: ./mediapipe/wasm). */
  readonly VITE_MEDIAPIPE_WASM_PATH?: string;
  /** Music track to play (default: the track generated by Tone.js). */
  readonly VITE_MUSIC_URL?: string;
}

interface ImportMeta {
  readonly env: ImportMetaEnv;
}
